"""DB

Revision ID: 0d59302e6c47
Revises: 
Create Date: 2024-09-09 21:52:51.751902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d59302e6c47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TransactionLogs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('BALANCE_REPLENISHMENT', 'BALANCE_WITHDRAWAL', name='transactionlogtype'), nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'idempotency_key', name='type_and_ik')
    )
    op.create_table('Posting',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('counteragent_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['TransactionLogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Posting')
    op.drop_table('TransactionLogs')
    # ### end Alembic commands ###
